name: CI

on:
  push:
    branches: [ main, juan ]
  pull_request:
    branches: [ main, juan ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: backend/api
        run: npm install
      - name: Run backend tests
        working-directory: backend/api
        run: npm test --silent

  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend deps
        working-directory: frontend/vite-app
        run: npm install
      - name: Build frontend
        working-directory: frontend/vite-app
        run: npm run build
